// Array de productos disponibles
const productos = [
  { name: "Coca Cola", precio: 190 },
  { name: "Coca Zero", precio: 190 },
  { name: "Sprite", precio: 190 },
  { name: "Monster Energy", precio: 260 },
  { name: "Agua", precio: 170 },
  { name: "Nescafe", precio: 170 },
  { name: "Burger Simple", precio: 260 },
  { name: "Burger Completa", precio: 320 },
  { name: "Pancho", precio: 160 },
  { name: "Scones", precio: 210 },
  { name: "Bon o Bon x3", precio: 70 },
  { name: "Cofler", precio: 190 },
  { name: "Mogul pie", precio: 130 },
  { name: "Chicle", precio: 60 },
  { name: "Menthoplus", precio: 60 },
  { name: "Turron", precio: 50 },
  { name: "Alfajor Triple", precio: 100 },
  { name: "Alfajor Simple", precio: 60 },
  { name: "Porteñitas", precio: 140 },
  { name: "Opera", precio: 140 },
  { name: "Rellena", precio: 140 },
  { name: "Papas", precio: 160 },
  { name: "Kesitas", precio: 160 },
  { name: "Saladix", precio: 160 },
  { name: "Pop", precio: 160 },
  { name: "Pizza", precio: 900 },
  { name: "Campeon Gourmet", precio: 2500 },
  { name: "Picada Carbonara", precio: 2300 },
  { name: "Sweet Time", precio: 1000 },
  { name: "Cervezas 0.0%", precio: 200 },
  { name: "Tubo Mogul", precio: 60 },
  { name: "Waffle", precio: 160 },
  { name: "Papas", precio: 160 },
  { name: "Papas tubo", precio: 300 },
];
