// Array de productos disponibles
const productos = [
  { producto: "Coca Cola", precio: 190 },
  { producto: "Coca Zero", precio: 190 },
  { producto: "Sprite", precio: 190 },
  { producto: "Monster Energy", precio: 260 },
  { producto: "Agua", precio: 170 },
  { producto: "Nescafe", precio: 170 },
  { producto: "Burger Simple", precio: 260 },
  { producto: "Burger Completa", precio: 320 },
  { producto: "Pancho", precio: 160 },
  { producto: "Scones", precio: 210 },
  { producto: "Bon o Bon x3", precio: 70 },
  { producto: "Cofler", precio: 190 },
  { producto: "Mogul pie", precio: 130 },
  { producto: "Chicle", precio: 60 },
  { producto: "Menthoplus", precio: 60 },
  { producto: "Turron", precio: 50 },
  { producto: "Alfajor Triple", precio: 100 },
  { producto: "Alfajor Simple", precio: 60 },
  { producto: "Porteñitas", precio: 140 },
  { producto: "Opera", precio: 140 },
  { producto: "Rellena", precio: 140 },
  { producto: "Papas", precio: 160 },
  { producto: "Kesitas", precio: 160 },
  { producto: "Saladix", precio: 160 },
  { producto: "Pop", precio: 160 },
  { producto: "Pizza", precio: 900 },
  { producto: "Campeon Gourmet", precio: 2500 },
  { producto: "Picada Carbonara", precio: 2300 },
  { producto: "Sweet Time", precio: 1000 },
  { producto: "Cervezas 0.0%", precio: 200 },
  { producto: "Tubo Mogul", precio: 60 },
  { producto: "Waffle", precio: 160 },
  { producto: "Papas", precio: 160 },
  { producto: "Papas tubo", precio: 300 },
];
